version: "3.9"

services:
  github-worker:
    container_name: github-worker
    build:
      dockerfile: Dockerfile
    restart: always
    networks:
      - proxy
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: admin
      RABBIT_PASS: admin123
      RABBIT_PORT: 5672

networks:
  proxy:
    external: true
